//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvertisementID { get; set; }
        public string Title { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Position { get; set; }
        public string Link { get; set; }
        public int CategoryID { get; set; }
    }
}
