//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticalCategory
    {
        public int ArticalCatID { get; set; }
        public string ArticalCatName { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsFix { get; set; }
    }
}
