//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_THONG_TIN
    {
        public int ID { get; set; }
        public string GroupInfo { get; set; }
        public string Info { get; set; }
        public string Value { get; set; }
        public string Des { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
