//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.InventoryDetails = new HashSet<InventoryDetail>();
        }
    
        public int InventoryID { get; set; }
        public string InventoryCode { get; set; }
        public int PeriodID { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public string InventoryBy { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual InventoryPeriod InventoryPeriod { get; set; }
        public virtual ICollection<InventoryDetail> InventoryDetails { get; set; }
    }
}
