//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryPeriod
    {
        public InventoryPeriod()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int PeriodID { get; set; }
        public string PeriodName { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
