//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int ProductMaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Desciption { get; set; }
    }
}
