//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SAN_PHAM_TTINH
    {
        public int ID { get; set; }
        public int ID_SAN_PHAM { get; set; }
        public string MA_SAN_PHAM { get; set; }
        public string MA_TTINH { get; set; }
        public string GIA_TRI { get; set; }
    }
}
