//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_TTINH_LOAI
    {
        public int ID { get; set; }
        public string MA_TTINH_LOAI { get; set; }
        public string TEN_TTINH_LOAI { get; set; }
    }
}
