//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrderDetail
    {
        public int StockOrderDetailID { get; set; }
        public Nullable<int> StockOrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Reason { get; set; }
    
        public virtual StockOrder StockOrder { get; set; }
    }
}
