//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENU
    {
        public string MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string MENU_NAME_EN { get; set; }
        public string MENU_TYPE { get; set; }
        public int DISPLAY_SEQ { get; set; }
        public string ICON_SEQ { get; set; }
        public string CONTROLER_NAME { get; set; }
        public string ACTION_NAME { get; set; }
        public string PARAMETER_NAMES { get; set; }
        public string PARAMETER_VALUES { get; set; }
        public string PARENT_ID { get; set; }
        public string REC_STATUS { get; set; }
        public string INPUTTER { get; set; }
        public string INPUT_DATE { get; set; }
        public string AUTHORISER { get; set; }
        public string AUTH_DATE { get; set; }
    }
}
