//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_VERSION
    {
        public int ID { get; set; }
        public string LOAI { get; set; }
        public string PHIEN_BAN { get; set; }
        public string MO_TA { get; set; }
    }
}
