//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductSet_Product
    {
        public int ProductSetID { get; set; }
        public string ProductSetCode { get; set; }
        public string ProductSetName { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public Nullable<int> ProductStyleID { get; set; }
        public Nullable<int> ProductMaterialID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public int Pocket { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> ForGender { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceSaled { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Description { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> ProductUnit { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> ProductDesignID { get; set; }
        public int Viewed { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
