//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebInfo
    {
        public int InforID { get; set; }
        public string NameLiveChat1 { get; set; }
        public string YahooLiveChat1 { get; set; }
        public string PhoneLiveChat1 { get; set; }
        public string NameLiveChat2 { get; set; }
        public string YahooLiveChat2 { get; set; }
        public string PhoneLiveChat2 { get; set; }
        public string HotLine1 { get; set; }
        public string HotLine2 { get; set; }
        public string NameSupport1 { get; set; }
        public string YahooSupport1 { get; set; }
        public string PhoneSupport1 { get; set; }
        public string NameSupport2 { get; set; }
        public string YahooSupport2 { get; set; }
        public string PhoneSupport2 { get; set; }
        public string SupportSale_Comp { get; set; }
        public string SupportSale_Address { get; set; }
        public string SupportSale_Email { get; set; }
        public string SupportSale_Web { get; set; }
        public string SupportSale_Phone1 { get; set; }
        public string SupportSale_Phone2 { get; set; }
        public string Bank_AcountName { get; set; }
        public string Bank1_Name { get; set; }
        public string Bank1_BranchName { get; set; }
        public string Bank1_Acount { get; set; }
        public byte[] Bank1_Logo { get; set; }
        public string Bank2_Name { get; set; }
        public string Bank2_BranchName { get; set; }
        public string Bank2_Acount { get; set; }
        public byte[] Bank2_Logo { get; set; }
        public string Bank3_Name { get; set; }
        public string Bank3_BranchName { get; set; }
        public string Bank3_Acount { get; set; }
        public byte[] Bank3_Logo { get; set; }
        public string TwitterLink { get; set; }
        public string FacebookLink { get; set; }
        public string GooglePlusLink { get; set; }
        public string YouTubeLink { get; set; }
    }
}
